name: ut_ad_leika
description: "A new Flutter project."

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.5"

dependencies:
  cupertino_icons: 1.0.8
  device_info_plus: 11.5.0
  equatable: 2.0.7
  event_bus: 2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  flutter_local_notifications: 19.3.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.2.0
  geolocator: ^13.0.2
  get_it: 8.0.3
  google_fonts: 6.2.1
  google_maps_flutter: ^2.10.0
  hive: 2.2.3
  injectable: 2.5.0
  intl: 0.20.2
  logger: 2.6.0
  lottie: 3.3.1
  shared_preferences: 2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: 1.2.1
  url_launcher: ^6.3.1
  uuid: 4.5.1

dev_dependencies:
  build_runner: 2.5.4
  flutter_gen_runner: 5.10.0
  flutter_launcher_icons: 0.14.4
  flutter_test:
    sdk: flutter
  injectable_generator: 2.7.0
  intl_utils: 2.8.10
  lint: 2.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/icons/flags/
    - assets/images/
    - assets/illustrations/light/
    - assets/illustrations/dark/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/love_assistant_logo.png"

flutter_gen:
  output: lib/presentation/core/assets
  line_length: 120
  assets:
    outputs:
      class_name: AppAssets

flutter_intl:
  main_locale: is
  enabled: true
  class_name: S
  arb_dir: lib/presentation/core/localization
  output_dir: lib/presentation/core/localization
  # to generate manually: dart run intl_utils:generate